name: Publish SDK (Dev)

on:
  push:
    branches:
      - "dev"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  publish-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none

      - name: Install Composer dependencies
        run: cd src && composer install --no-interaction --prefer-dist --no-progress

      - name: Create sqlite database
        run: cd src && touch database/database.sqlite

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
          scope: "@apidockit-com"

      - name: Install npm dependencies for documentation
        working-directory: tools/documentation
        run: npm ci

      - name: Generate OpenAPI YAML and SDK
        working-directory: tools/documentation
        run: npm run generate

      - name: Generate new SDK version number
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: |
          echo "NEW_SDK_VERSION=$(node tools/documentation/semantic-version-dev.mjs)" >> $GITHUB_ENV

      - name: Print new SDK version
        run: |
          echo "Next SDK version: ${{ env.NEW_SDK_VERSION }}"

      - name: Install SDK dependencies
        working-directory: openapi/sdk
        run: npm install

      - name: Set NPM Package Version
        working-directory: openapi/sdk
        run: npm version "${{ env.NEW_SDK_VERSION }}" --allow-same-version --no-git-tag-version

      - name: Build SDK
        working-directory: openapi/sdk
        run: npm run build

      - name: Publish SDK to GitHub Packages
        working-directory: openapi/sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: npm publish --tag dev

      - name: Summary
        run: |
          echo "## SDK Published Successfully ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** \`${{ env.NEW_SDK_VERSION }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Tag:** \`dev\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Install command:**" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "npm install @apidockit-com/sdk@${{ env.NEW_SDK_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
